Resources:
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ${self:provider.stage}-${self:service}
  GatewayResponseResourceNotFound:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      RestApiId:
        Ref: 'ApiGatewayRestApi'
      ResponseType: BAD_REQUEST_BODY
      "StatusCode" : "422"
      ResponseTemplates:
        application/json: "{\"message\": \"$context.error.message\", \"error\": \"$context.error.validationErrorString\"}"